praxismethoden/urls.py
from os import name
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("timeline", views.timeline, name="timeline"), 
    path("alle", views.alle, name="alle"), 
    path("meine", views.meine, name="meine"),
    path("course", views.course, name="course"),
    path("methoden/<int:method_id>", views.method_single, name="method_single"), # single method view
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # staff only
    path("staff", views.staff_view, name="staff"),
    path("methoden/<int:method_id>/edit", views.method_single_edit, name="method_single_edit"),
    path("methoden/<int:method_id>/edit/file", views.method_single_edit_file, name="method_single_edit_file"),
    path("methoden/new", views.new_method, name="new_method"),
    path("methoden/delete/<int:method_id>", views.method_delete, name="method_delete"),

    # api routes
    path("api/methoden/<int:method_id>", views.api_method_single, name="api_method_single"),
    path("api/methoden/<str:category>", views.category, name="category"),
    path("api/all_categories", views.all_categories, name="all_categories"),
    path("api/all_methods", views.all_methods, name="all_methods"),
]

sgpb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("praxismethoden.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

praxismethoden/models.py
from cloudinary_storage.storage import RawMediaCloudinaryStorage
from django.contrib.auth.models import AbstractUser
from django.db import models
from ckeditor.fields import RichTextField
from django.db.models.base import Model
from django.db.models.deletion import CASCADE

class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=255)

    def lower(self):
        return self.name.lower()

    def serialize(self):
        return {
            "id": self.id,
            "name": self.name,
            "name_lower": self.name.lower(),
        }

    def __str__(self):
        return f'Kategorie {self.id}: {self.name}'

class Method(models.Model):
    likes = models.ManyToManyField("User", related_name="methods_liked", blank=True)
    titel = models.CharField(max_length=255)
    desc = RichTextField(null=True, blank=True, verbose_name="Beschreibung", help_text="Der hier eingegebene Text beschreibt die Methode.")
    tipp = RichTextField(null=True, blank=True, verbose_name="Tipp", help_text="Hier noch ein Text, welcher als Tipp zur Methode angezeigt wird.")
    timestamp = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField("Category", related_name="categories_method", blank=True)
    files = models.ManyToManyField('File', related_name="method_files", blank=True)


    def serialize(self):
        
        return {
            "id": self.id,
            "likes": [user.id for user in self.likes.all()],
            "titel": self.titel,
            "desc": self.desc,
            "tipp": self.tipp,
            "timestamp": self.timestamp.strftime("%b %d %Y, %I:%M %p"),
            "category": {
                "id": [cat.id for cat in self.category.all()],
                "name": [cat.name for cat in self.category.all()],
            } if self.category else { },
            "files": {
                "name": [f.file_name for f in self.files.all()],
                "url": [f.file.url for f in self.files.all()],
            } if self.files else { },
        }

    def __str__(self):
        return f'{self.id}: {self.titel}, zuletzt geändert: {self.timestamp}'    

class File(models.Model):
    file_name = models.CharField(max_length=255)
    file = models.FileField(upload_to='raw/', storage=RawMediaCloudinaryStorage(), verbose_name="Dokument")

    def __str__(self):
        return f'{self.id}: {self.file_name}'

class Course(models.Model):
    owner = models.ForeignKey(
        User,
        related_name='courses_created',
        on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)  
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(User, related_name="students", blank=True)

    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.title

MODULE_KINDS = (
    (1, 'Meilenstein'),
    (2, 'Prüfungsleistung')
)

class Module(models.Model):
    course = models.ForeignKey(
        Course,
        related_name='modules',
        on_delete=CASCADE
    )
    module_kind = models.PositiveSmallIntegerField(choices=MODULE_KINDS, default=1, verbose_name="Art des Elements")
    title = models.CharField(max_length=255)
    summary = models.TextField(max_length=510)
    desc = RichTextField(null=True, blank=True, verbose_name="Zusammenfassung", help_text="Der hier eingegebene Text beschreibt die kurz das wichtigste zum Meilenstein.")
    tipp = RichTextField(null=True, blank=True, verbose_name="Tipp", help_text="Hier noch ein Text, welcher als Tipp zur Methode angezeigt wird.")
    files = models.ManyToManyField('File', related_name="module_files", blank=True)


    def __str__(self):
        return self.title

PRIO_CHOICES = (
    (1,'Hoch'),
    (2, 'Mittel'),
    (3,'Tief'),
)

praxismethoden/forms.py
from .models import Method, File
from django import forms


class MethodForm(forms.ModelForm):
    class Meta:
        model = Method
        fields = '__all__'
        exclude = ['likes']
        # widgets = {             'file_raw': forms.FileInput(attrs={'multiple': True}),         }

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = '__all__'

praxismethoden/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.core.checks.messages import Error
from django.db import IntegrityError
from django.forms import HiddenInput, fields, formset_factory
from django.forms.formsets import formset_factory
from django.forms.models import modelformset_factory
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse
from django.urls.base import reverse_lazy
from .models import Category, File, User, Method
from .forms import MethodForm, FileForm
from django.contrib.admin.views.decorators import staff_member_required

# Course View and Admin

def course(request):
    course = request.user.students.last()

    return render(request, "praxismethoden/course.html", {
        "course": course
    })

# Hauptseiten

def index(request):
    return render(request, "praxismethoden/index.html", {
        
    })

def timeline(request):
    return render(request, "praxismethoden/timeline.html")

def alle(request):
    cards = Method.objects.all()
    categories = Category.objects.all()
    return render(request, "praxismethoden/methodenansicht.html", {
        "seiten_titel": "Methoden",
        "cards": cards,
        "categories": categories,
        "titel": "Alle Methoden",
        "untertitel": "Hier findest du die aktuellen Methoden der Projektbox. Mit deinem Feedback werden sie laufend aktualisiert."
    })

@login_required(login_url='login')
def meine(request):
    cards = Method.objects.filter(likes=request.user)
    return render(request, "praxismethoden/methodenansicht.html", {
        "seiten_titel": "Favoriten",
        "cards": cards,
        "titel": "Favoriten",
        "untertitel": "Hier findest du deine favoritisierten Methoden."
    })

def method_single(request, method_id):
    m = Method.objects.get(pk=method_id)
    # f = m.method_files.all()
    return render(request, "praxismethoden/single_methodenansicht.html", {
        "method": m
    })

# Staff Member Views

@staff_member_required()
def staff_view(request):

    m = Method.objects.all()
    u = User.objects.filter(is_staff=False)
    return render(request, "praxismethoden/staff/overview.html", {
        "titel": "Betreuenden Ansicht",
        "all_methods": m,
        "users": u
    })
        
@login_required(login_url='login')
def method_single_edit(request, method_id):

    if request.user.is_staff:
        m = Method.objects.get(pk=method_id)
        f = MethodForm(instance=m)
        files_formset = modelformset_factory(
            File, form = FileForm, can_delete = True,
        )
        if request.method == "POST":
            f = MethodForm(request.POST, instance=m)
            if f.is_valid():
                f.save()
                return render(request, "praxismethoden/staff/single_edit_methodenansicht.html", {
                    "id": method_id,
                    "form": f,
                    "file_form": files_formset,
                    "method": m
                })
        else:
            return render(request, "praxismethoden/staff/single_edit_methodenansicht.html", {
                "id": method_id,
                "form": f,
                "file_form": files_formset,
                "method": m
            })
    else:
        return HttpResponseRedirect(reverse("method_single", kwargs={'method_id': method_id})) 

@staff_member_required()
def method_single_edit_file(request, method_id):
    if request.method == "POST":
        files_formset = modelformset_factory(File, fields="__all__", can_delete=True)
        formset = files_formset(request.POST, request.FILES)
        if formset.is_valid():
            instances = formset.save(commit=False)
            for obj in formset.deleted_objects:
                obj.delete()
            for i in instances:
                i.save()
            return HttpResponseRedirect(reverse("method_single_edit", kwargs={'method_id': method_id}))
        else:
            print(formset.errors)
            return HttpResponseRedirect(reverse("method_single_edit", kwargs={'method_id': method_id}))
    else:
        return HttpResponseRedirect(reverse("method_single_edit", kwargs={'method_id': method_id}))

@staff_member_required()
def new_method(request):
    f = MethodForm()
    if request.method == "POST":
        f = MethodForm(request.POST)
        if f.is_valid():
            f.save()
            return HttpResponseRedirect(reverse("staff"))
        else:
            return render(request, "praxismethoden/staff/new_method.html", {
                "form": f,
            })
    else:
        return render(request, "praxismethoden/staff/new_method.html", {
                "form": f,
            })

@staff_member_required()
def method_delete(request, method_id):
    m = Method.objects.get(pk=method_id)
    m.delete()
    return redirect("staff")

# account

def email_check(user):
    return user.email.endswith('unisg.ch')

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, username=email, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "praxismethoden/login.html", {
                "message": "Invalid email and/or password."
            })
    else:
        return render(request, "praxismethoden/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        email = request.POST["email"]
        first_name = request.POST["firstname"]
        last_name = request.POST["lastname"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "praxismethoden/register.html", {
                "message": "Passwörter müssen übereinstimmen."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(email, email, password, first_name=first_name, last_name=last_name)
            user.save()
        except IntegrityError as e:
            print(e)
            return render(request, "praxismethoden/register.html", {
                "message": "Diese E-Mail ist schon vergeben."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "praxismethoden/register.html")


# api

def api_method_single(request, method_id):

    # Query for requested method
    try:
        m = Method.objects.get(pk=method_id)
    except Method.DoesNotExist:
        return JsonResponse({"error": "Method not found."}, status=404)

    # Return method contents
    if request.method == "GET":
        return JsonResponse(m.serialize())

    elif request.method == "POST":
        data = json.loads(request.body)
        if data.get("like") == True:
            m.likes.remove(request.user)
        else:
            m.likes.add(request.user)
        m.save()
        return HttpResponse(status=204)

    # Email must be via GET or PUT
    else:
        return JsonResponse({
            "error": "GET or PUT request required."
        }, status=400)

def all_methods(request):
    
    all_m = Method.objects.all()
    return JsonResponse([m.serialize() for m in all_m], safe=False)

def all_categories(request):
    
    all_cat = Category.objects.all()
    return JsonResponse([cat.serialize() for cat in all_cat], safe=False)

def category(request, category):

    try:
        cat = Category.objects.get(name_lower=category.lower())
    except Method.DoesNotExist:
        return JsonResponse({"error": "Method not found."}, status=404)

    methods = Method.objects.filter(category=cat)
    return JsonResponse([method.serialize() for method in methods], safe=False)
    

praxismethoden/templates/praxismethoden/staff/new_method.html
{% extends "praxismethoden/layout.html" %}
{% load static %}

{% block script %}
    <script>
        $(document).ready(function() {
            $('#id_files').select2({
                width: '100%'
            });
            $('#id_category').select2({
                width: '100%'
            });
        });
    </script>
{% endblock %}

{% block body %}
<div class="row" id="alle">
    <div class="col-12 mt-3">
        <a class="btn btn-outline-secondary mb-3" href="{% url 'staff' %}" role="button">Zurück</a>
        <h1 class="display-6 fw-bold">Edit: {{ method.titel }} </h1>        
    </div>      

    <form action="{% url 'new_method' %}" method="post">
        {% csrf_token %}
        {{ form.media }}
        {% for field in form %}
            <div class="mb-3 col-12 col-lg-8">
                {{ field.errors }}
                <div class="form-label">
                    {{ field.label_tag }}
                </div>
                {{ field }}
                {% if field.help_text %}
                    <div class="form-text">{{ field.help_text|safe }}</div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Änderungen speichern</button>
    </form>
</div>
{% endblock %}

praxismethoden/templates/praxismethoden/staff/overview.html
{% extends "praxismethoden/layout.html" %}
{% load static %}

{% block script %}

{% endblock %}

{% block body %}
<div class="py-3 py-md-5">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fw-bold">{{ titel }} </h1>
        <p class="lead my-3"> {{ untertitel }} </p>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col-12">
        <h3>Alle Methoden</h3>
        <ul>
            {% for m in all_methods %}
                <li>{{ m.titel }} - <a href="{% url 'method_single_edit' m.id %}">Bearbeiten</a></li>
            {% endfor %}
        </ul>
        <a href="{% url 'new_method' %}" class="btn btn-primary">Neue Methode</a>
    </div>
    <div class="col-12 mt-3">
        <h3>Nutzer und Methoden</h3>
    </div>
    
    {% for user in users %}

    <div class="col-12 col-md-6 col-lg-5 mb-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ user.id }}: {{ user.first_name }} {{ user.last_name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ user.email }}</h6>
                
                {% if user.methods_liked.all %}
                    <ul class="list-group">
                        {% for m in user.methods_liked.all %}  
                        <li class="list-group-item">

                            {{ m.id }}: {{ m.titel }}
                            
                        </li>
                        {% endfor %}
                    </ul>     
                
                {% else %}
                    <p>Keine Methoden gefunden.</p>                        
                {% endif %}

            </div>
        </div>
    </div>

    {% endfor %}
    
</div>



{% endblock %}

praxismethoden/templates/praxismethoden/staff/single_edit_methodenansicht.html
{% extends "praxismethoden/layout.html" %}
{% load static %}

{% block script %}

    <script>
        $(document).ready(function() {
            $('#id_files').select2({
                width: '100%'
            });
            $('#id_category').select2({
                width: '100%'
            });
        });
    </script>
{% endblock %}

{% block body %}
<div class="row" id="alle">
    <div class="col-12 mt-3">
        <a class="btn btn-outline-secondary mb-3" href="{% url 'staff' %}" role="button">Zurück</a>
        <h1 class="display-6 fw-bold">Edit: {{ method.titel }} </h1>        
    </div>      
    <div class="alert-warning">
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
    <form action="{% url 'method_single_edit' id %}" method="post">
        {% csrf_token %}
        {{ form.media }}
        {% for field in form %}
            <div class="mb-3 col-12 col-lg-8">
                {{ field.errors }}
                <div class="form-label">
                    {{ field.label_tag }}
                </div>
                {{ field }}
                {% if field.help_text %}
                    <div class="form-text">{{ field.help_text|safe }}</div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Änderungen speichern</button>
        <a id="method_delete" href="{% url 'method_delete' id %}" class="ml-3 btn btn-danger">Methode Löschen</a>
    </form>
    <div class="col-12 pt-5">
        <h2>Dateien</h2>
    </div>
    <div class="col-12 col-lg-8">
        <form class="accordion" id="filesAccordion" action="{% url 'method_single_edit_file' id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ file_form.management_form }}
            {% for form in file_form %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="file-{{ form.id.value }}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ form.id.value }}" aria-expanded="false" aria-controls="collapse{{ form.id.value }}">
                            {{ form.file_name.value|default:"Neue Datei" }}
                        </button>
                    </h2>
                    <div id="collapse{{ form.id.value }}" class="accordion-collapse collapse" aria-labelledby="file-{{ form.id.value }}" data-bs-parent="#filesAccordion">
                        <div class="accordion-body">
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in form.visible_fields %}
                            <div class="d-flex flex-wrap w-100">
                                {{ field.errors }}
                                <div class="col-12 col-md-3 form-label">
                                    {{ field.label_tag }}
                                </div>
                                <div class="col text-break">
                                    {{ field }}
                                </div>
                                {% if field.help_text %}
                                    <div class="form-text">{{ field.help_text|safe }}</div>
                                {% endif %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary mt-3">Änderungen speichern</button>
        </form>
    </div>
    
</div>
{% endblock %}